runtime: custom
env: flex
service: angular-app-cloud

runtime_config:
  runtime_version: "nodejs22"
  operating_system: "ubuntu22"

instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  NODE_ENV: "production"

handlers:
- url: /(.*)
  static_files: dist/angular-app/index.html
  upload: dist/angular-app/index.html
- url: /
  static_dir: dist/angular-app
