runtime: python39  # You can use other runtimes like `nodejs` if you want to but for static content, python works well
env: standard  # Use the standard environment for static files

instance_class: F2  # You can adjust this based on the instance class you'd like to use

handlers:
  # Serve the index.html file (default route)
  - url: /
    static_files: dist/my-angular-app/index.html
    upload: dist/my-angular-app/index.html

  # Serve static assets (JS, CSS, images, etc.)
  - url: /assets
    static_dir: dist/my-angular-app/assets

  # Serve other static files (JS, CSS, etc.)
  - url: /(.*)
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*)

env_variables:
  NODE_ENV: "production"
