runtime: nodejs22.13.1
env: flex
service: angular-app

instance_class: F2

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  NODE_ENV: "production"

handlers:
- url: /
  static_files: dist/my-angular-app/index.html
  upload: dist/my-angular-app/index.html

- url: /(.*)
  static_files: dist/my-angular-app/\1
  upload: dist/my-angular-app/(.*)

- url: /assets
  static_dir: dist/my-angular-app/assets
